### ISSUE TITLE
API Test Drive graph time window > 1m leads to "no data"

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#11]
After submitting about 40 examples in the Test Drive, the graph was still blank.  I changed the "show results for the past:" menu down to 1m, and lines showed up.  I changed it back to 1h, and the graph says "no data" again.  It seems odd that changing that interval should lead to presence vs. absence of anything on the graph.

**Comment by lhoang29** [comment]
when did you do the deployment? What resource group is this?

**Comment by danmelamed** [comment]
Deployment DMDP5 at 1:36PM.  Alas, it was in my own subscription.  I will try to replicate in our shared subscription.

**Comment by sidsen** [comment]
I was able to repro this in my subscription. Basically, at the beginning only data for 1m shows up while the other options show "no data available". After about 40min I saw one datapoint in the 1h plot (but sitll nothing for the longer windows); the x-axis marks for the 1h plot did not make sense either.

This seems worse than how things were in the morning -- could this be a regression caused by some other fix/change?
