### ISSUE TITLE
clip average reward to the range of possible rewards, i.e. [0,1]

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#18]
Can't do this in VW, but should be doable in the Test Drive JavaScript.  It would eliminate a source of confusion/distraction.

**Comment by lhoang29** [comment]
Do you mean to clip the graph at 0-1 on the y-axis?

**Comment by lhoang29** [comment]
Had a chat with Dan offline, we'll instead add text to let users know that it's normal for values in the graph to be more than 1, and refer them to whitepaper for more details on how the calculation is done.

**Comment by sidsen** [comment]
I think the idea was to constrain the y-values to be in [0,1], not to clip the y-axis view of the graph. John seems to be fine with truncating y values to max(y,1).

**Comment by eisber** [comment]
Min(1,y)?!

**Comment by lhoang29** [comment]
Seems to me the primary source of this issue is the confusion that Average Reward usually means taking average of 0,1 values which should not be > 1. If we clarify the result, that should be good enough? The truncation alternative means we also need to explain what we do in addition to the IPS estimate if someone actually followed the whitepaper (otherwise they'd be again confused).

**Comment by eisber** [comment]
using self-normalized IPS
