### ISSUE TITLE
API Test Drive ignores input

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#4]
There seems to be a heisenbug where the API Test Drive ignores the input information.    I can't trigger this reliable, but it just happened on 3 out of 5 "successful" deployments this morning.   The signature of this bug is the message:

Trainer OK.  Total learned examples: <small fixed constant>

where <small fixed constant> was 1 or 7.    The graph is also messed up because of this.  The relevant deployments are foo-9, foo-11, and foo-12 in our test account.

**Comment by JohnLangford** [comment]
The form of this bug has changed a little bit, but it continues to exist.  Now it says:

Trainer OK. Total learned examples: 0

foo-7, foo-6, foo-3, foo-2  (4 out of 8 tries) exhibit this problem.

**Comment by JohnLangford** [comment]
Oh!  Correction: If I reload the page, things look reasonable.  There appears to be a problem where the first line of information can cease to update in a bad state and then it (and the graph) never update until the page is refreshed.

**Comment by sidsen** [comment]
I was able to create a situation where the number of examples wasn't
updating but examples were being reported, indicating they never made it to
the online learner. I didn't have time to nail down the repro steps so I'll
update this thread when I do.

Note part of the problem is we don't have an API that allows you to specify
infinite exp unit duration and just report-reward-and-complete-event
manually (i added this API for the local machine DS). So every browser
refresh or plot refresh or any >10s idling results in completed events with
no reward signal.

Sid

On Jul 1, 2016 9:58 PM, "John" <notifications@github.com> wrote:

>

> Oh! Correction: If I reload the page, things look reasonable. There
appears to be a problem where the first line of information can cease to
update in a bad state and then it (and the graph) never update until the
page is refreshed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/mwt-ds/issues/4#issuecomment-230077803>, or
mute the thread
<https://github.com/notifications/unsubscribe/AAPASqiiZnl9jynSXL8Nyy5pUdDhWXEJks5qRcWwgaJpZM4JDMxK>
.

**Comment by JohnLangford** [comment]
For me, the number of examples was set to 0 (or, alternatively, the system
was reporting that it could not query the trainer).  Then, I did a reload,
and suddenly the number of examples jumped to 104 (which is approximately
correct).

-John

**Comment by sidsen** [comment]
Fyi, according to the code the number of training examples should update
every 10 seconds (irrespective of reward reporting clicks).

**Comment by JohnLangford** [comment]
Definitely not happening.

-John

**Comment by lhoang29** [comment]
I think I fixed this issue, try again.

**Comment by JohnLangford** [comment]
It looks fixed to me, although maybe not perfectly?  I saw a jump from no trained example to 85 happen.

**Comment by lhoang29** [comment]
Probably because of the update timeout we set on the website, it's currently 15 secs.

**Comment by sidsen** [comment]
Louie, I thought we call trainerStatus every 10 seconds, not 15. Is that right?

**Comment by lhoang29** [comment]
It's 15 (recently changed)

**Comment by eisber** [comment]
@JohnLangford comment " I saw a jump from no trained example to 85 happen." ASA does batching to improve throughput
